# Generated by Django 5.0.3 on 2024-04-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(default='Indian', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(default='Jungle Themed', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='food_img_url_1',
            field=models.CharField(default='../assets/img1.png', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='food_img_url_2',
            field=models.CharField(default='../assets/img2/png', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='img_url',
            field=models.CharField(default='../assets/bg2.jpeg', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.CharField(default='Anna Nagar, Chennai', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=3.9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='type',
            field=models.CharField(default='Non-Veg', max_length=10),
            preserve_default=False,
        ),
    ]
